### ISSUE TITLE
BL-001 - “Dead-end” flows (resource limits) 

### ISSUE THREAD

**Issue by mootz12** [blend-capital/blend-contracts#159]
From Certora Security Report.

There is a potential dead-end flow where a user can amass a large amount of positions and become un-liquidatable due to the health check failing for resource limitations.

Recommended Fix:
* Limit the number of positions a user can have

**Comment by markuspluna** [comment]
Resolved in
https://github.com/blend-capital/blend-contracts/pull/174
Which allows pool admins to set a max_positions cap to prevent user's from putting their account in a state where they can't be liquidated due to resource limits

This solution was chosen over a less flexible one (like hardcoding a max position limit) because resource limits are expected to rise over time, thus locking the protocol into a low cap would harm protocol long-term utility
