### ISSUE TITLE
Backstop: Drop List Expiration

### ISSUE THREAD

**Issue by markuspluna** [blend-capital/blend-contracts#202]
The drop_list in Backstop is initialized and [stored in temporary storage](https://github.com/blend-capital/blend-contracts/blob/main/backstop/src/storage.rs#L477) during [initial setup](https://github.com/blend-capital/blend-contracts/blob/main/backstop/src/contract.rs#L196), intended for a [one-time emission drop](https://github.com/blend-capital/blend-contracts/blob/main/emitter/src/emitter.rs#L21). If the [drop function](https://github.com/blend-capital/blend-contracts/blob/main/backstop/src/contract.rs#L308) is not triggered in time, leading to the expiration of the temporary storage, the contract fails to receive the drop. 

We should move the drop list to persistent storage as temporary storage expiration during the backstop swap process is possible.

**Comment by mootz12** [comment]
@markuspluna I'm leaning towards won't fix for this one.

For the first backstop implementation, it will be more efficient to track this in temporary storage as it will only be needed after the contract has been deployed, and there is no risk of not having enough time due to no backstop swap occurring.

If a backstop swap is occurring, the backstop being swapped to can make this change (if deemed necessary).

If you don't have concerns with this - would you mind closing the issue?

**Comment by markuspluna** [comment]
That sounds fine
